title = "v2ray admin"

[server]
port = 8085

[postgres]
# 配置参数 https://pkg.go.dev/github.com/lib/pq
dbname = "v2ray-admin"
user = "va"
password = "123456"
host = "localhost"
port = 5432
sslmode = "disable"
# - Whether or not to use SSL (default is require, this is not the default for libpq)
# fallback_application_name =
# - An application_name to fall back to if one isn't provided.
# connect_timeout =
# - Maximum wait for connection, in seconds. Zero or not specified means wait indefinitely.
# sslcert =
# - Cert file location. The file must contain PEM encoded data.
# sslkey =
# - Key file location. The file must contain PEM encoded data.
# sslrootcert =
# - The location of the root certificate file. The file must contain PEM encoded data.

[xorm]
max_idle = 4
max_open = 8
show_sql = true
sync = true
cache_enable = false
cache_count = 1000

[cache]
manager = "redis"
# redis | memory , default memory

[redis]
enable = true
host = "localhost"
port = 6379
pool_max_idle = 4
poll_max_active = 8

[smtp]
host = "smtp.mail.com"
password = "passwd"
port = 465
username = "someone@mail.com"
from = "v2ray admin"

[v2ray]
host = "192.168.2.210"
port = 8998
tag = "proxy"
level_range = "1-12"
config_file = "./v2ray-server-config.json"

[conf_tpl]
address = "192.168.2.210"
port = 80
alter_id = 4
security = "auto"
network = "ws"
type = "none"
host = ""
path = "/home"
tls = ""
allow_insecure = "false"